import { createHash } from "node:crypto";
import { lstat, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

type Scope = "production" | "synthetic-test";

interface PromptManifestV1 {
  readonly manifestVersion: 1;
  readonly entries: readonly {
    readonly promptId: string;
    readonly promptVersion: number;
    readonly sha256: string;
    readonly relativePath: string;
  }[];
}

const locations = {
  production: {
    root: "src/ai/prompts/resources/production",
    manifest: "src/ai/prompts/resources/production/manifest.v1.json",
    output: "src/ai/prompts/generated/production-prompt-bundle.generated.ts",
    markerName: "CWT_PRODUCTION_PROMPT_BUNDLE_MARKER",
    marker: "CWT_SERVER_AI_PROMPT_BUNDLE_V1_91B6E4A3",
    exportName: "productionPromptBundleV1",
  },
  "synthetic-test": {
    root: "src/ai/testing/synthetic-prompts/resources",
    manifest: "src/ai/testing/synthetic-prompts/manifest.v1.json",
    output: "src/ai/testing/synthetic-prompts/synthetic-prompt-bundle.generated.ts",
    markerName: "CWT_SYNTHETIC_PROMPT_BUNDLE_MARKER",
    marker: "CWT_SYNTHETIC_TEST_DATA_NOT_A_CWT_FACT_V1",
    exportName: "syntheticPromptBundleV1",
  },
} as const;

function parseManifest(bytes: Buffer): PromptManifestV1 {
  const input: unknown = JSON.parse(bytes.toString("utf8"));
  if (typeof input !== "object" || input === null || Array.isArray(input)) {
    throw new Error("Prompt manifest must be one object.");
  }
  const record = Object.fromEntries(Object.entries(input));
  if (Object.keys(record).sort().join(",") !== "entries,manifestVersion" ||
    record.manifestVersion !== 1 || !Array.isArray(record.entries)) {
    throw new Error("Prompt manifest contract is invalid.");
  }
  const entries: PromptManifestV1["entries"][number][] = [];
  for (const entry of record.entries) {
    if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
      throw new Error("Prompt manifest entry is invalid.");
    }
    const value = Object.fromEntries(Object.entries(entry));
    if (Object.keys(value).sort().join(",") !== "promptId,promptVersion,relativePath,sha256" ||
      typeof value.promptId !== "string" || typeof value.promptVersion !== "number" ||
      typeof value.sha256 !== "string" || typeof value.relativePath !== "string") {
      throw new Error("Prompt manifest entry contract is invalid.");
    }
    entries.push({
      promptId: value.promptId,
      promptVersion: value.promptVersion,
      sha256: value.sha256,
      relativePath: value.relativePath,
    });
  }
  return { manifestVersion: 1, entries };
}

export async function generatePromptBundleText(scope: Scope): Promise<string> {
  const location = locations[scope];
  const manifest = parseManifest(await readFile(resolve(location.manifest)));
  const output: string[] = [
    "// Generated by scripts/generate-ai-prompt-bundle.ts. Do not edit.",
    `export const ${location.markerName} =`,
    `  ${JSON.stringify(location.marker)};`,
    "",
    `export const ${location.exportName} = [`,
  ];
  let priorId = "";
  let priorVersion = 0;
  const tupleKeys = new Set<string>();
  const paths = new Set<string>();
  const hashes = new Set<string>();
  for (const entry of manifest.entries) {
    const expectedPath = `${entry.promptId}/v${entry.promptVersion}.${entry.sha256}.json`;
    if (
      !/^[a-z][a-z0-9-]{0,63}$/.test(entry.promptId) ||
      !Number.isInteger(entry.promptVersion) || entry.promptVersion < 1 ||
      !/^[0-9a-f]{64}$/.test(entry.sha256) || entry.relativePath !== expectedPath ||
      entry.relativePath.includes("..") || entry.relativePath.includes("\\") ||
      entry.relativePath.includes("%") || entry.relativePath.startsWith("/")
    ) throw new Error("Prompt manifest tuple/path is invalid.");
    if (entry.promptId < priorId ||
      (entry.promptId === priorId && entry.promptVersion <= priorVersion)) {
      throw new Error("Prompt manifest order is invalid.");
    }
    if (entry.promptId !== priorId && entry.promptVersion !== 1) {
      throw new Error("A Prompt ID must begin at version 1.");
    }
    if (entry.promptId === priorId && entry.promptVersion !== priorVersion + 1) {
      throw new Error("Prompt versions must be consecutive.");
    }
    const tupleKey = `${entry.promptId}:${entry.promptVersion}`;
    if (tupleKeys.has(tupleKey) || paths.has(entry.relativePath) || hashes.has(entry.sha256)) {
      throw new Error("Prompt manifest contains a duplicate authority tuple.");
    }
    tupleKeys.add(tupleKey);
    paths.add(entry.relativePath);
    hashes.add(entry.sha256);
    const resourcePath = resolve(location.root, entry.relativePath);
    const info = await lstat(resourcePath);
    if (!info.isFile() || info.isSymbolicLink()) throw new Error("Prompt resource must be a regular file.");
    const raw = await readFile(resourcePath);
    if (raw.byteLength === 0 || raw.byteLength > 32_768 || raw[raw.length - 1] !== 0x0a ||
      createHash("sha256").update(raw).digest("hex") !== entry.sha256) {
      throw new Error("Prompt resource bytes/hash are invalid.");
    }
    if (scope === "production" && raw.includes(Buffer.from("SYNTHETIC TEST DATA — NOT A CWT FACT"))) {
      throw new Error("Synthetic content cannot enter Production Prompt authority.");
    }
    if (scope === "synthetic-test" && !raw.includes(Buffer.from("SYNTHETIC TEST DATA — NOT A CWT FACT"))) {
      throw new Error("Synthetic Prompt resources require the conspicuous marker.");
    }
    output.push("  {");
    output.push(`    promptId: ${JSON.stringify(entry.promptId)},`);
    output.push(`    promptVersion: ${entry.promptVersion},`);
    output.push(`    sha256: ${JSON.stringify(entry.sha256)},`);
    output.push(`    relativePath: ${JSON.stringify(entry.relativePath)},`);
    output.push(`    rawByteLength: ${raw.byteLength},`);
    output.push(`    rawBase64: ${JSON.stringify(raw.toString("base64"))},`);
    output.push("  },");
    priorId = entry.promptId;
    priorVersion = entry.promptVersion;
  }
  output.push("] as const;");
  output.push("");
  return output.join("\n");
}

async function main(): Promise<void> {
  const argument = process.argv[2];
  const scopeValue = process.argv[3];
  if (argument !== "--scope" || (scopeValue !== "production" && scopeValue !== "synthetic-test") || process.argv.length !== 4) {
    throw new Error("Usage: tsx scripts/generate-ai-prompt-bundle.ts --scope production|synthetic-test");
  }
  await writeFile(resolve(locations[scopeValue].output), await generatePromptBundleText(scopeValue), "utf8");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  void main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : "Prompt generation failed.");
    process.exitCode = 1;
  });
}
